name: Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      - run: make build && sh tests/test.sh
